### ISSUE TITLE
Maybe emit a post `Saving` event just before calling `save()` in `chore:reparse`?

### ISSUE THREAD

**Issue by n-peugnet** [club-1/flarum-ext-chore-commands#2]
It seems to be the logical thing to do but I am not sure how this event is used in practice by extension developers, so it may lead to unexpected behaviour.

Sorry to bother you @rob006, but since you were interested in this reparse command, do you have any opinion about this?

**Comment by rob006** [comment]
I have no idea. But from quick search in my forum it would bring only additional overhead, as all listeners for this event seem to target actual user interaction and all of them have some kind of condition that would skip execution in reparse scenario.  But gamification handles rate limiting in this event. I don't think it will trigger in this case, but other extensions may listen to this event and they may complain about save frequency.

I would rather suggest to skip this event in this case, unless you find case where lack of this event creates some problems.

**Comment by n-peugnet** [comment]
Thanks! Let's close this and reopen it if the need shows up.
